### PR TITLE
add: jumping functionality, refactored using unity input system

### PR DESCRIPTION
**Pull request by cameronzhang1**
WASD movement refactored for the player with jump animations in the prison level using the unity input system package.
The script AnimationAndMovementController.cs is where the majority of changes are made, if you guys can review it would be awesome.

### CODE REVIEW

**Comment by juancwu** [comment]
@cameronzhang1 Do you need to add a script to the player prefab or you can just include the player prefab in the scene and it will work?

**Comment by cameronzhang1** [comment]
> @cameronzhang1 Do you need to add a script to the player prefab or you can just include the player prefab in the scene and it will work?

Experimenting with it right now in the garden level, I think you need to manually add the script. Ill see what I can change to optimize it.

**Comment by juancwu** [comment]
> > @cameronzhang1 Do you need to add a script to the player prefab or you can just include the player prefab in the scene and it will work?
> 
> @juancwu Experimenting with it right now in the garden level, I think you need to manually add the script. Ill see what I can change to optimize it.

Try not to optimize too much, we should be focus on working on other features that is going to be in the final product.

**Comment by juancwu** [comment]
Looking good!
Take the Castle - Garden - Windows, Mac, Linux - Unity 2021 3 12f1 Personal _DX11_ 2023-01-16 18-34-39

**Review by Mathuran-Mang — APPROVED** [review]
Looks good

**Review by andrew-pejko — APPROVED** [review]
works well!!

**Pull request merged**
